version: 0.0
os: linux

hooks:
   ApplicationStop:
      -  location: scripts/stop_cont.sh
         timeout: 300
         runas: root
   AfterInstall:
      -  location: scripts/start_cont.sh
         timeout: 300
         runas: root